### ISSUE TITLE
The gruntfile doesn't work

### ISSUE THREAD

**Issue by altano** [webpack/the-big-test#1]
I'm trying to get code-coverage integration with my mocha tests and so I thought I would experiment with running the tests using webpack and the coverjs-loader.  I stumbled into this project but it looks like it is in a non-functioning state right now:

```
>grunt
Running "webpack:test" (webpack) task
Warning: Function.prototype.toString is not generic Use --force to continue.

Aborted due to warnings.
```

I'd like to keep all testing of my webpack project in node.js rather than doing it in a browser or phantomJS.  Are there any examples of webpack + testing + code coverage?  I  don't even care if it's mocha or coverjs or anything: I just want webpack + tests + code coverage.

In the mean time, I'm going to investigate why this project isn't working since it is a good start.  That first error is related to the inlineWorkerPlugin: I just need to figure out what it's non-obvious purpose is.

**Comment by sokra** [comment]
Fixed stuff in 73178e94cd8281f4bc48369f1a3ccefad2b5f1cd

For testing see: http://webpack.github.io/docs/testing.html
